import "./globals.css";
import { Inter, Poppins } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import SesssionWrapper from "./SessionProvider";
import { EdgeStoreProvider } from "@/lib/edgestore";

const inter = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Cognito",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
        />
      </head>
      <SesssionWrapper>
        <EdgeStoreProvider>
          <body className={`${inter.className} bg-white`}>
            <NextUIProvider>{children}</NextUIProvider>
          </body>
        </EdgeStoreProvider>
      </SesssionWrapper>
    </html>
  );
}
